# Generated by Django 4.2.3 on 2023-07-24 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format  71000000.', regex='^\\d{8}$')]),
        ),
    ]
