# Generated by Django 4.2.3 on 2023-07-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='score_parameters',
        ),
        migrations.AddField(
            model_name='client',
            name='score_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.scoreparameters'),
        ),
    ]
