# Generated by Django 4.2.3 on 2023-07-25 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_score_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='score_parameters',
        ),
        migrations.AddField(
            model_name='scoreparameters',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_parameters', to=settings.AUTH_USER_MODEL),
        ),
    ]
