# Generated by Django 4.1.6 on 2023-07-25 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_score_parameters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurCommerciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_client', models.IntegerField(blank=True, choices=[(None, 'Unspecified'), (0, 'Standard'), (1, 'VIP')], default=None, null=True)),
                ('engagement_contractuel', models.IntegerField(blank=True, choices=[(None, 'Unspecified'), (0, 'Engagé'), (1, 'Non Engagé')], default=None, null=True)),
                ('offre', models.DecimalField(blank=True, choices=[(None, 'Unspecified'), (0.5, 'XDSL'), (1, 'HD')], decimal_places=1, default=None, max_digits=3, null=True)),
                ('debit', models.PositiveIntegerField(blank=True, choices=[(None, 'Unspecified'), (100, 1), (50, 0.9), (30, 0.8), (20, 0.7), (12, 0.6), (10, 0.4), (8, 0.2), (4, 0)], default=None, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ValeurCommerciale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
