# Generated by Django 4.1.6 on 2023-07-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_engagementclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurcommerciale',
            name='debit',
            field=models.PositiveIntegerField(blank=True, choices=[(None, 'Unspecified'), (1, 100), (0.9, 50), (0.8, 30), (0.7, 20), (0.6, 12), (0.4, 10), (0.2, 8), (0, 4)], default=None, null=True),
        ),
    ]
