# Generated by Django 4.1.6 on 2023-07-25 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_valeurcommerciale_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementclient',
            name='anciennete',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementclient',
            name='montant_en_cours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementclient',
            name='nombre_suspension',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EngagementTopnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reclamation', models.FloatField(blank=True, null=True)),
                ('delai_traitement', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_topnet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
