# Generated by Django 4.1.6 on 2023-07-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_engagementclient_anciennete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementclient',
            name='anciennete',
        ),
        migrations.RemoveField(
            model_name='engagementclient',
            name='montant_en_cours',
        ),
        migrations.RemoveField(
            model_name='engagementclient',
            name='nombre_suspension',
        ),
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='delai_traitement',
        ),
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='nombre_reclamation',
        ),
    ]
