# Generated by Django 4.2.3 on 2023-07-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_engagementclient_anciennete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComportementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComportementClient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
