# Generated by Django 4.2.3 on 2023-07-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_facture_contineux'),
        ('client', '0010_comportementclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='comportementclient',
            name='facture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ComportementClient', to='facture.facture'),
        ),
    ]
