# Generated by Django 4.2.3 on 2023-07-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_valeurcommerciale_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurcommerciale',
            name='debit',
            field=models.DecimalField(blank=True, choices=[(None, 'Unspecified'), ('1', '100'), ('0.9', '50'), ('0.8', '30'), ('0.7', '20'), ('0.6', '12'), ('0.4', '10'), ('0.2', '8'), ('0', '4')], decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
