# Generated by Django 4.2.3 on 2023-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_valeurcommerciale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.FloatField(default=0),
        ),
    ]
