# Generated by Django 4.1.6 on 2023-07-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_engagementtopnet_delai_traitement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='delai_traitement',
        ),
    ]
