# Generated by Django 4.1.6 on 2023-07-29 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_alter_scoreparameters_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreparameters',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='score_parameters',
        ),
        migrations.AlterField(
            model_name='scoreparameters',
            name='comportement_client_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight for Comportement Client axis (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scoreparameters',
            name='engagement_client_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight for Engagement Client axis (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scoreparameters',
            name='engagement_topnet_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight for Engagement TOPNET axis (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scoreparameters',
            name='valeur_commerciale_weight',
            field=models.PositiveIntegerField(default=25, help_text='Weight for Valeur Commerciale axis (0 to 100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
