# Generated by Django 4.1.6 on 2023-07-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_alter_scoreparameters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementtopnet',
            name='nombre_reclamations',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.BooleanField(default=False),
        ),
    ]
