# Generated by Django 4.1.6 on 2023-07-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_engagementtopnet_nombre_reclamations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='delai_traitement',
        ),
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='nombre_reclamations',
        ),
    ]
