# Generated by Django 4.1.6 on 2023-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_remove_engagementtopnet_delai_traitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='engagementtopnet',
            name='nombre_reclamations',
            field=models.FloatField(default=0),
        ),
    ]
