# Generated by Django 4.1.6 on 2023-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_engagementtopnet_delai_traitement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.IntegerField(default=0),
        ),
    ]
