# Generated by Django 4.1.6 on 2023-07-29 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_alter_engagementtopnet_delai_traitement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementtopnet',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
