# Generated by Django 4.1.6 on 2023-07-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_alter_engagementtopnet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='engagementtopnet',
            name='nombre_reclamations',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
