# Generated by Django 4.1.6 on 2023-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_alter_engagementtopnet_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.FloatField(default=0),
        ),
    ]
