# Generated by Django 4.1.6 on 2023-07-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_alter_engagementtopnet_nombre_reclamations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='score_parameters',
        ),
    ]
