# Generated by Django 4.1.6 on 2023-07-30 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_remove_client_score_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='score_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_score_parameters', to='client.scoreparameters'),
        ),
        migrations.AddField(
            model_name='comportementclient',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comportement_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
