# Generated by Django 4.1.6 on 2023-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_client_score_parameters_comportementclient_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
