# Generated by Django 4.1.6 on 2023-07-31 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_axes'),
    ]

    operations = [
        migrations.AddField(
            model_name='axes',
            name='client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Axes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='axes',
            name='comportement_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.comportementclient'),
        ),
        migrations.AddField(
            model_name='axes',
            name='engagement_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.engagementclient'),
        ),
        migrations.AddField(
            model_name='axes',
            name='engagement_topnet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.engagementtopnet'),
        ),
        migrations.AddField(
            model_name='axes',
            name='valeur_commerciale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.valeurcommerciale'),
        ),
    ]
