# Generated by Django 4.1.6 on 2023-07-31 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_axes_client_axes_comportement_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='score_parameters',
        ),
        migrations.AddField(
            model_name='comportementclient',
            name='axes_relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comportement_client_relation', to='client.axes'),
        ),
        migrations.AddField(
            model_name='engagementclient',
            name='axes_relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_client_relation', to='client.axes'),
        ),
        migrations.AddField(
            model_name='engagementtopnet',
            name='axes_relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_topnet_relation', to='client.axes'),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='axes_relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_commerciale_relation', to='client.axes'),
        ),
        migrations.AlterField(
            model_name='valeurcommerciale',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_commerciale', to=settings.AUTH_USER_MODEL),
        ),
    ]
