# Generated by Django 4.1.6 on 2023-07-31 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_remove_client_score_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Axes', to=settings.AUTH_USER_MODEL),
        ),
    ]
