# Generated by Django 4.1.6 on 2023-07-31 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_alter_axes_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axes',
            name='comportement_client',
            field=models.OneToOneField(blank=True, limit_choices_to={'client': django.db.models.expressions.OuterRef('client')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.comportementclient'),
        ),
        migrations.AlterField(
            model_name='axes',
            name='engagement_client',
            field=models.OneToOneField(blank=True, limit_choices_to={'client': django.db.models.expressions.OuterRef('client')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.engagementclient'),
        ),
        migrations.AlterField(
            model_name='axes',
            name='engagement_topnet',
            field=models.OneToOneField(blank=True, limit_choices_to={'client': django.db.models.expressions.OuterRef('client')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.engagementtopnet'),
        ),
        migrations.AlterField(
            model_name='axes',
            name='valeur_commerciale',
            field=models.OneToOneField(blank=True, limit_choices_to={'client': django.db.models.expressions.OuterRef('client')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.valeurcommerciale'),
        ),
    ]
