# Generated by Django 4.1.6 on 2023-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_alter_axes_client_alter_axes_comportement_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axes',
            name='weight_comportement_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='axes',
            name='weight_engagement_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='axes',
            name='weight_engagement_topnet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='axes',
            name='weight_valeur_commerciale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
