# Generated by Django 4.1.6 on 2023-08-01 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0044_alter_axes_comportement_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Axes', to=settings.AUTH_USER_MODEL),
        ),
    ]
