# Generated by Django 4.1.6 on 2023-08-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_alter_axes_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='axes',
            name='comportement_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.comportementclient'),
        ),
        migrations.AlterField(
            model_name='axes',
            name='engagement_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.engagementclient'),
        ),
        migrations.AlterField(
            model_name='axes',
            name='engagement_topnet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.engagementtopnet'),
        ),
        migrations.AlterField(
            model_name='axes',
            name='valeur_commerciale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.valeurcommerciale'),
        ),
    ]
