# Generated by Django 4.1.6 on 2023-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0048_alter_axes_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementclient',
            name='poids_anciennete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='engagementclient',
            name='poids_montant_en_cours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='engagementclient',
            name='poids_nombre_suspension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='poids_categorie_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='poids_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='poids_engagement_contractuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='poids_offre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
