# Generated by Django 4.1.6 on 2023-08-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_comportementclient_poids_contentieux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='delai_traitement',
        ),
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='nombre_reclamations',
        ),
        migrations.AddField(
            model_name='engagementtopnet',
            name='poids_delai_traitement',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='engagementtopnet',
            name='poids_nombre_reclamations',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
