# Generated by Django 4.1.6 on 2023-08-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0051_remove_engagementtopnet_delai_traitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementtopnet',
            name='delai_traitement',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='engagementtopnet',
            name='nombre_reclamations',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
