# Generated by Django 4.1.6 on 2023-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_engagementtopnet_delai_traitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeurcommerciale',
            name='objectif_categorie_client',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='objectif_debit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='objectif_engagement_contractuel',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='valeurcommerciale',
            name='objectif_offre',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
