# Generated by Django 4.1.6 on 2023-08-03 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0054_remove_valeurcommerciale_objectif_categorie_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axes',
            name='weight_comportement_client',
        ),
        migrations.RemoveField(
            model_name='axes',
            name='weight_engagement_client',
        ),
        migrations.RemoveField(
            model_name='axes',
            name='weight_engagement_topnet',
        ),
        migrations.RemoveField(
            model_name='axes',
            name='weight_valeur_commerciale',
        ),
        migrations.RemoveField(
            model_name='comportementclient',
            name='poids_contentieux',
        ),
        migrations.RemoveField(
            model_name='comportementclient',
            name='poids_delai_moyen_paiement',
        ),
        migrations.RemoveField(
            model_name='comportementclient',
            name='poids_incident_de_paiement',
        ),
        migrations.RemoveField(
            model_name='engagementclient',
            name='poids_anciennete',
        ),
        migrations.RemoveField(
            model_name='engagementclient',
            name='poids_montant_en_cours',
        ),
        migrations.RemoveField(
            model_name='engagementclient',
            name='poids_nombre_suspension',
        ),
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='poids_delai_traitement',
        ),
        migrations.RemoveField(
            model_name='engagementtopnet',
            name='poids_nombre_reclamations',
        ),
        migrations.RemoveField(
            model_name='valeurcommerciale',
            name='poids_categorie_client',
        ),
        migrations.RemoveField(
            model_name='valeurcommerciale',
            name='poids_debit',
        ),
        migrations.RemoveField(
            model_name='valeurcommerciale',
            name='poids_engagement_contractuel',
        ),
        migrations.RemoveField(
            model_name='valeurcommerciale',
            name='poids_offre',
        ),
        migrations.CreateModel(
            name='CriteriaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_offre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_debit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_categorie_client', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_engagement_contractuel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_nombre_suspension', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_montant_en_cours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_delai_moyen_paiement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_incident_de_paiement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_contentieux', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_weights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AxesWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_commerciale_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_topnet_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('engagement_client_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comportement_client_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes_weights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
