# Generated by Django 4.1.6 on 2023-08-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0055_remove_axes_weight_comportement_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axesweight',
            name='client',
        ),
        migrations.RemoveField(
            model_name='criteriaweight',
            name='client',
        ),
    ]
