# Generated by Django 4.1.6 on 2023-08-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0056_remove_axesweight_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriaweight',
            name='poids_delai_traitement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='criteriaweight',
            name='poids_nombre_reclamations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
