# Generated by Django 4.1.6 on 2023-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0057_criteriaweight_poids_delai_traitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axes',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
