# Generated by Django 4.1.6 on 2023-08-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0058_axes_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axes',
            name='total_score',
        ),
    ]
