# Generated by Django 4.1.6 on 2023-08-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0059_remove_axes_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='axesweight',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
