# Generated by Django 4.1.6 on 2023-08-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0061_criteriaweight_active_axes_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaweight',
            name='active_axes_weight',
            field=models.BooleanField(default=False),
        ),
    ]
