# Generated by Django 4.2.3 on 2023-07-24 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('Id_reclamation', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='contrat.contrat')),
            ],
        ),
    ]
