# Generated by Django 4.1.6 on 2023-07-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0003_reclamation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='client',
        ),
    ]
