# Generated by Django 4.1.6 on 2023-07-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reclamation', '0004_remove_reclamation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
    ]
