# Generated by Django 4.2.3 on 2023-07-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=128),
        ),
    ]
