# Generated by Django 4.2.3 on 2023-07-24 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('Id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('montant_encours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(max_length=100)),
                ('date_du_facture', models.DateField(default=django.utils.timezone.now)),
                ('date_a_payer_avant', models.DateField()),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='contrat.contrat')),
            ],
        ),
    ]
