# Generated by Django 4.2.3 on 2023-07-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_paiement',
            field=models.CharField(choices=[('Espece', 'Espece'), ('CreditCard', 'Credit Card'), ('Cheque', 'Cheque')], max_length=100),
        ),
    ]
