# Generated by Django 4.2.3 on 2023-07-24 18:53

from django.db import migrations, models
import facture.models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_alter_facture_type_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='statut_paiement',
            field=models.CharField(choices=[('rejet', 'Rejet'), ('non', 'Non')], default='non', max_length=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_a_payer_avant',
            field=models.DateField(validators=[facture.models.validate_date_a_payer_avant]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_encours',
            field=models.DecimalField(decimal_places=2, help_text='Montant en Dinar Tunisien', max_digits=10),
        ),
    ]
