# Generated by Django 4.2.3 on 2023-07-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_facture_contineux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='contineux',
        ),
    ]
