# Generated by Django 4.2.3 on 2023-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_remove_facture_contineux'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='contineux',
            field=models.BooleanField(default=False),
        ),
    ]
