# Generated by Django 4.2.3 on 2023-07-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_facture_contineux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='contineux',
            new_name='contentieux',
        ),
    ]
