# Generated by Django 4.2.3 on 2023-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0007_rename_contineux_facture_contentieux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='contentieux',
            field=models.BooleanField(choices=[(False, 1), (True, 0)], default=False),
        ),
    ]
